version: '3.8'

services:
  frontend-api:
    build: ./frontend_api
    container_name: frontend-api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
  
  backend-api:
    build: ./backend
    ports:
      - "8001:8000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"
  
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_ERL_COOKIE=YOUR_SECRET_COOKIE
    ports:
      - "5672:5672"  # RabbitMQ main port
      - "15672:15672"  # RabbitMQ Management UI
